---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "alertmanager-discord.fullname" . }}
  labels:
    {{- include "alertmanager-discord.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-webhook: '{.data[''webhook'']}'
type: Opaque
stringData:
  webkook: {{ .Values.discord.webhook }}
