{{- $fullname := include "alertmanager-discord.fullname" . -}}
---
{{- if not .Values.sealedSecrets.enable }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "alertmanager-discord.labels" . | nindent 4 }}
  annotations:
    template.openshift.io/expose-webhook: '{.data[''webhook'']}'
type: Opaque
stringData:
  webhook: {{ .Values.discord.webhook }}
{{- else }}
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: {{ .Release.Namespace }}-{{ $fullname }}
  namespace: {{ .Values.sealedSecrets.namespace }}
  labels:
    {{- include "alertmanager-discord.labels" . | nindent 4 }}
spec:
  encryptedData:
    webhook: {{ .Values.discord.webhook }}
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: {{ .Release.Name }}
        meta.helm.sh/release-namespace: {{ .Release.Namespace }}
        sealed-secret.bitnami.com/name: {{ .Release.Namespace }}-{{ $fullname }}
        sealed-secret.bitnami.com/namespace: {{ .Values.sealedSecrets.namespace }}
        template.openshift.io/expose-webhook: '{.data[''webhook'']}'
      labels:
        {{- include "alertmanager-discord.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/managed-by: SealedSecrets
        app.kubernetes.io/managing-namespace: {{ .Values.sealedSecrets.namespace }}
      name: {{ $fullname }}
      namespace:  {{ .Release.Namespace }}
    type: Opaque
{{- end }}

