# Default values for alertmanager-discord.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

discord:
  webhook: URL-FROM-DISCORD

image:
  repository: quay.io/klenkes74/alertmanager-discord
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

networkpolicy:
  label: "network.openshift.io/policy-group: monitoring"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
