# Default values for alertmanager-discord.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

discord:
  webhook: URL-FROM-DISCORD

sealedSecrets:
  enable: false
  namespace: kube-system


image:
  repository: quay.io/klenkes74/alertmanager-discord
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  k8s-ttl-controller.twin.sh/ttl: "24h"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

networkpolicy:
  label: "network.openshift.io/policy-group: monitoring"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 20m
    memory: 32Mi
  limits:
    cpu: 20m
    memory: 32Mi

nodeSelector: {}

tolerations: []

affinity: {}
